openapi: 3.0.0
info:
  title: Simple API
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8000
paths:
  /getResponse:
    post:
      # summary: Say Hello
      operationId: sayHello
      requestBody:
        # description: Input message to personalize the greeting
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  # description: The query of user
      responses:
        "200":
          # description: Successful response
          content:
            text/plain:
              schema:
                type: string
                # example: "Hello, Alice!"
